/*drop table XBBNHCY_USER;
drop table XBBNHCY_ADMIN;
drop table XBBNHCY_QUESTION;
drop table XBBNHCY_ANSWER;
drop table XBBNHCY_VOTES;

select * from XBBNHCY_ANSWER;
select * from XBBNHCY_USER;
select * from XBBNHCY_QUESTION;
select * from XBBNHCY_ADMIN;
select * from XBBNHCY_VOTES;*/

CREATE TABLE XBBNHCY_USER
(
UserID int NOT NULL PRIMARY KEY CHECK (UserID>0),
Name varchar(100) NOT NULL,
Email varchar(100) NOT NULL UNIQUE,
Username varchar(100) NOT NULL UNIQUE,
Password varchar(100) NOT NULL check (LENGTH(Password) >= 8)
);

CREATE TABLE XBBNHCY_ADMIN
(
AdminID int NOT NULL PRIMARY KEY,
Username varchar(100) NOT NULL UNIQUE,
Password varchar(100) NOT NULL check (LENGTH(Password) >= 8)
);


CREATE TABLE XBBNHCY_QUESTION
(
QuestionID int NOT NULL PRIMARY KEY,
Title varchar(300) NOT NULL,
QuestionBody varchar2(2000),
UserID int NOT NULL,

CONSTRAINT FK_Q_U FOREIGN KEY (UserID)
REFERENCES XBBNHCY_USER(UserID)

);


CREATE TABLE XBBNHCY_ANSWER
(
AnswerID int NOT NULL PRIMARY KEY,
Answer varchar(200) NOT NULL,
UserID int NOT NULL,
QuestionID int NOT NULL,
CONSTRAINT FK_A_U FOREIGN KEY (UserID)
REFERENCES XBBNHCY_USER(UserID),
CONSTRAINT FK_A_Q FOREIGN KEY (QuestionID)
REFERENCES XBBNHCY_QUESTION(QuestionID)
);

CREATE TABLE XBBNHCY_VOTES
(
VoteID int NOT NULL PRIMARY KEY,
Vote int DEFAULT 0,
AnswerID int NOT NULL,
CONSTRAINT FK_V_A FOREIGN KEY (AnswerID)
REFERENCES XBBNHCY_ANSWER(AnswerID)
);
