SELECT U.Name, Q.Title FROM XBBNHCY_USER U JOIN XBBNHCY_QUESTION Q ON U.UserID = Q.UserID;
SELECT U.Name, A.Answer FROM XBBNHCY_USER U JOIN XBBNHCY_ANSWER A ON U.UserID = A.UserID;
SELECT Q.Title, A.Answer ,U.Name as Answerer FROM XBBNHCY_ANSWER A JOIN XBBNHCY_QUESTION Q ON Q.QuestionID = A.QuestionID JOIN XBBNHCY_USER U ON A.UserID = U.UserID;

